// generated by compile -asmhdr from package ffi

#define const_type64 0x0
#define const_typeS32 0x1
#define const_typeU32 0x2
#define const_typeS16 0x3
#define const_typeU16 0x4
#define const_typeS8 0x5
#define const_typeU8 0x6
#define const_typeDouble 0x7
#define const_typeFloat 0x8
#define const_typeUnused 0xffff
#define argument__size 4
#define argument_offset 0
#define argument_t 2
#define Spec__size 120
#define Spec_fn 0
#define Spec_base 8
#define Spec_stack 16
#define Spec_intargs 40
#define Spec_xmmargs 64
#define Spec_ret0 96
#define Spec_ret1 100
#define Spec_xmmret0 104
#define Spec_xmmret1 108
#define Spec_rax 112
#define emptyComplex64__size 8
#define emptyComplex64_a 0
