// Code generated by cmd/cgo; DO NOT EDIT.

//line b.go:1:1
package main

/*
#include <stdio.h>
extern int cb(int);
int test_cb() {
	int res;
	printf("in C!\n");
	res = cb(10);
	printf("in C again: %d\n", res);
	return res*2;
}
*/
import _ "unsafe"
