// Code generated by cmd/cgo; DO NOT EDIT.

//line main.go:1:1
package main

// #include <stdio.h>
// #include <stdlib.h>
// #include <string.h>
import _ "unsafe"

import "unsafe"

func main() {
	cs := []byte("Hello\000 world\000")
	(_Cfunc_puts)((*_Ctype_char)(unsafe.Pointer(&cs[0])))
	func(_cgo0 *_Ctype_char, _cgo1 *_Ctype_struct__IO_FILE) _Ctype_int {;	_cgoCheckPointer(_cgo1);	return (_Cfunc_fputs)(_cgo0, _cgo1);}((*_Ctype_char)(unsafe.Pointer(&cs[0])), (_Cmacro_stdout()))
	func(_cgo0 _Ctype_int, _cgo1 *_Ctype_struct__IO_FILE) _Ctype_int {;	_cgoCheckPointer(_cgo1);	return (_Cfunc_putc)(_cgo0, _cgo1);}('a', (_Cmacro_stdout()))
	(_Cfunc_strcat)((*_Ctype_char)(unsafe.Pointer(&cs[0])), (*_Ctype_char)(unsafe.Pointer(&cs[0])))
	(_Cfunc_puts)((*_Ctype_char)(unsafe.Pointer(&cs[0])))
}
